package com.kh.sammi;

import java.util.Date;

public class Realestate {
	
	// 留ㅻЪ踰덊샇
	private int REALESTATE_ID; 
	// 以묎컻�씤踰덊샇
	private int INTERMEDIARY_ID;
	// 留ㅻЪ�씠由�
	private String REALESTATE_NAME;
	// 留ㅻЪ二쇱냼
	private String REALESTATE_ADDRESS;
	// 留ㅻЪ �쑀�삎
	private String REALESTATE_TYPE;
	// 怨꾩빟議곌굔
	private String REALESTATE_CONDITION;
	// 硫댁쟻
	private double REALESTATE_AREA;
	// 痢듭닔
	private String FLOORS;
	// 諛⑷컻�닔
	private int ROOMS_COUNT;
	// �솕�옣�떎媛쒖닔
	private int TOILET_COUNT;
	// 留ㅻℓ媛�
	private int REALESTATE_SALEPRICE;
	// �썡�꽭
	private int REALESTATE_MONTHLY;
	// 愿�由щ퉬
	private int REALESTATE_MAINTENANCE_COST;
	// �엯二쇨��뒫�씪
	private Date AVAILABLE_MOVE_IN_DATE;
	// 二쇱감媛��뒫�닔
	private int PARKING_COUNT;
	// �샃�뀡
	private String REALESTATE_OPTIION;
	// 留ㅻЪ�궗吏�
	private String REALESTATE_PHOTOS;
	// 湲고��궡�슜
	private String OTHER_COMMENT;
	// �벑濡앸궇吏�
	private Date REALESTATE_DATE;
	
	public Realestate(int REALESTATE_ID, int INTERMEDIARY_ID, String REALESTATE_NAME, String REALESTATE_ADDRESS, String REALESTATE_TYPE, String REALESTATE_CONDITION, double REALESTATE_AREA, String FLOORS, int ROOMS_COUNT, int TOILET_COUNT, 
			int REALESTATE_SALEPRICE, int REALESTATE_MONTHLY, int REALESTATE_MAINTENANCE_COST, Date AVAILABLE_MOVE_IN_DATE, int PARKING_COUNT, String REALESTATE_OPTIION, String REALESTATE_PHOTOS, String OTHER_COMMENT, Date REALESTATE_DATE) {
		this.REALESTATE_ID = REALESTATE_ID;
		this.INTERMEDIARY_ID = INTERMEDIARY_ID;
		this.REALESTATE_NAME = REALESTATE_NAME;
		this.REALESTATE_ADDRESS = REALESTATE_ADDRESS;
		this.REALESTATE_TYPE = REALESTATE_TYPE;
		this.REALESTATE_CONDITION = REALESTATE_CONDITION;
		this.REALESTATE_AREA = REALESTATE_AREA;
		this.FLOORS = FLOORS;
		this.ROOMS_COUNT = ROOMS_COUNT;
		this.TOILET_COUNT =TOILET_COUNT;
		this.REALESTATE_SALEPRICE = REALESTATE_SALEPRICE;
		this.REALESTATE_MONTHLY = REALESTATE_MONTHLY;
		this.REALESTATE_MAINTENANCE_COST = REALESTATE_MAINTENANCE_COST;
		this.AVAILABLE_MOVE_IN_DATE = AVAILABLE_MOVE_IN_DATE;
		this.PARKING_COUNT = PARKING_COUNT;
		this.REALESTATE_OPTIION = REALESTATE_OPTIION;
		this.REALESTATE_PHOTOS = REALESTATE_PHOTOS;
		this.OTHER_COMMENT = OTHER_COMMENT;
		this.REALESTATE_DATE = REALESTATE_DATE;
	}
	
	public Realestate(int REALESTATE_ID, String REALESTATE_CONDITION, int REALESTATE_SALEPRICE, int REALESTATE_MONTHLY, int REALESTATE_MAINTENANCE_COST, String REALESTATE_TYPE,
			double REALESTATE_AREA, String FLOORS, int ROOMS_COUNT, int TOILET_COUNT, int PARKING_COUNT, String REALESTATE_PHOTOS) {
		this.REALESTATE_ID = REALESTATE_ID;
		this.REALESTATE_TYPE = REALESTATE_TYPE;
		this.REALESTATE_CONDITION = REALESTATE_CONDITION;
		this.REALESTATE_AREA = REALESTATE_AREA;
		this.FLOORS = FLOORS;
		this.ROOMS_COUNT = ROOMS_COUNT;
		this.TOILET_COUNT =TOILET_COUNT;
		this.REALESTATE_SALEPRICE = REALESTATE_SALEPRICE;
		this.REALESTATE_MONTHLY = REALESTATE_MONTHLY;
		this.REALESTATE_MAINTENANCE_COST = REALESTATE_MAINTENANCE_COST;
		this.PARKING_COUNT = PARKING_COUNT;
		this.REALESTATE_PHOTOS = REALESTATE_PHOTOS;
	}
	
	
	
	public int getREALESTATE_ID() {
		return REALESTATE_ID;
	}
	public void setREALESTATE_ID(int rEALESTATE_ID) {
		REALESTATE_ID = rEALESTATE_ID;
	}
	public int getINTERMEDIARY_ID() {
		return INTERMEDIARY_ID;
	}
	public void setINTERMEDIARY_ID(int iNTERMEDIARY_ID) {
		INTERMEDIARY_ID = iNTERMEDIARY_ID;
	}
	public String getREALESTATE_NAME() {
		return REALESTATE_NAME;
	}
	public void setREALESTATE_NAME(String rEALESTATE_NAME) {
		REALESTATE_NAME = rEALESTATE_NAME;
	}
	public String getREALESTATE_ADDRESS() {
		return REALESTATE_ADDRESS;
	}
	public void setREALESTATE_ADDRESS(String rEALESTATE_ADDRESS) {
		REALESTATE_ADDRESS = rEALESTATE_ADDRESS;
	}
	public String getREALESTATE_TYPE() {
		return REALESTATE_TYPE;
	}
	public void setREALESTATE_TYPE(String rEALESTATE_TYPE) {
		REALESTATE_TYPE = rEALESTATE_TYPE;
	}
	public String getREALESTATE_CONDITION() {
		return REALESTATE_CONDITION;
	}
	public void setREALESTATE_CONDITION(String rEALESTATE_CONDITION) {
		REALESTATE_CONDITION = rEALESTATE_CONDITION;
	}
	public double getREALESTATE_AREA() {
		return REALESTATE_AREA;
	}
	public void setREALESTATE_AREA(double rEALESTATE_AREA) {
		REALESTATE_AREA = rEALESTATE_AREA;
	}
	public String getFLOORS() {
		return FLOORS;
	}
	public void setFLOORS(String fLOORS) {
		FLOORS = fLOORS;
	}
	public int getROOMS_COUNT() {
		return ROOMS_COUNT;
	}
	public void setROOMS_COUNT(int rOOMS_COUNT) {
		ROOMS_COUNT = rOOMS_COUNT;
	}
	public int getTOILET_COUNT() {
		return TOILET_COUNT;
	}
	public void setTOILET_COUNT(int tOILET_COUNT) {
		TOILET_COUNT = tOILET_COUNT;
	}
	public int getREALESTATE_SALEPRICE() {
		return REALESTATE_SALEPRICE;
	}
	public void setREALESTATE_SALEPRICE(int rEALESTATE_SALEPRICE) {
		REALESTATE_SALEPRICE = rEALESTATE_SALEPRICE;
	}
	public int getREALESTATE_MONTHLY() {
		return REALESTATE_MONTHLY;
	}
	public void setREALESTATE_MONTHLY(int rEALESTATE_MONTHLY) {
		REALESTATE_MONTHLY = rEALESTATE_MONTHLY;
	}
	public int getREALESTATE_MAINTENANCE_COST() {
		return REALESTATE_MAINTENANCE_COST;
	}
	public void setREALESTATE_MAINTENANCE_COST(int rEALESTATE_MAINTENANCE_COST) {
		REALESTATE_MAINTENANCE_COST = rEALESTATE_MAINTENANCE_COST;
	}
	public Date getAVAILABLE_MOVE_IN_DATE() {
		return AVAILABLE_MOVE_IN_DATE;
	}
	public void setAVAILABLE_MOVE_IN_DATE(Date aVAILABLE_MOVE_IN_DATE) {
		AVAILABLE_MOVE_IN_DATE = aVAILABLE_MOVE_IN_DATE;
	}
	public int getPARKING_COUNT() {
		return PARKING_COUNT;
	}
	public void setPARKING_COUNT(int pARKING_COUNT) {
		PARKING_COUNT = pARKING_COUNT;
	}
	public String getREALESTATE_OPTIION() {
		return REALESTATE_OPTIION;
	}
	public void setREALESTATE_OPTIION(String rEALESTATE_OPTIION) {
		REALESTATE_OPTIION = rEALESTATE_OPTIION;
	}
	public String getREALESTATE_PHOTOS() {
		return REALESTATE_PHOTOS;
	}
	public void setREALESTATE_PHOTOS(String rEALESTATE_PHOTOS) {
		REALESTATE_PHOTOS = rEALESTATE_PHOTOS;
	}
	public String getOTHER_COMMENT() {
		return OTHER_COMMENT;
	}
	public void setOTHER_COMMENT(String oTHER_COMMENT) {
		OTHER_COMMENT = oTHER_COMMENT;
	}
	public Date getREALESTATE_DATE() {
		return REALESTATE_DATE;
	}
	public void setREALESTATE_DATE(Date rEALESTATE_DATE) {
		REALESTATE_DATE = rEALESTATE_DATE;
	}
	
	
	



}